# This is free and unencumbered software released into the public domain.

[sources.host_source]
filesystem.mountpoints.excludes = ["*/proc/sys/fs/binfmt_misc"]
type = "host_metrics"

[sinks.host_prometheus]
endpoint = "http://10.25.0.3:9428/api/v1/write"
healthcheck.enabled = false
inputs = ["host_source"]
type = "prometheus_remote_write"
