# This is free and unencumbered software released into the public domain.

name: adguardhome

on:
  pull_request:
    paths: ['**/adguardhome.yaml', 'adguardhome/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['adguardhome/src/**']
  workflow_dispatch:

jobs:
  adguardhome:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: adguardhome/src/adguardhome.dockerfile }
