# This is free and unencumbered software released into the public domain.

name: alpine

on:
  pull_request:
    paths: ['**/alpine.yaml', 'alpine/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['alpine/src/**']
  workflow_dispatch:

jobs:
  alpine:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: alpine }
