# This is free and unencumbered software released into the public domain.

name: bootc

on:
  pull_request:
    paths: ['**/ops/**', '**bootc**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/ops/**', '**bootc**']
  workflow_dispatch:

jobs:
  bootc:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: bootc/src/bootc.dockerfile }
