# This is free and unencumbered software released into the public domain.

name: caddy

on:
  pull_request:
    paths: ['**/caddy.yaml', 'caddy/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['caddy/src/**']
  workflow_dispatch:

jobs:
  caddy:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: caddy }
