# This is free and unencumbered software released into the public domain.

name: chartdb

on:
  pull_request:
    paths: ['**/chartdb.yaml', 'chartdb/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['chartdb/src/**']
  workflow_dispatch:

jobs:
  chartdb:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: chartdb }
