# This is free and unencumbered software released into the public domain.

name: crowdsec

on:
  pull_request:
    paths: ['**/crowdsec.yaml', 'crowdsec/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['crowdsec/src/**']
  workflow_dispatch:

jobs:
  crowdsec:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: crowdsec/src/crowdsec.dockerfile }
