# This is free and unencumbered software released into the public domain.

name: fossflow

on:
  pull_request:
    paths: ['**/fossflow.yaml', 'fossflow/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['fossflow/src/**']
  workflow_dispatch:

jobs:
  fossflow:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: fossflow }
