# This is free and unencumbered software released into the public domain.

name: gitea

on:
  pull_request:
    paths: ['**/gitea.yaml', 'gitea/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['gitea/src/**']
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: gitea/src/server.dockerfile }
