# This is free and unencumbered software released into the public domain.

name: grafana

on:
  pull_request:
    paths: ['**/grafana.yaml', 'grafana/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['grafana/src/**']
  workflow_dispatch:

jobs:
  grafana:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: grafana/src/grafana.dockerfile }
