# This is free and unencumbered software released into the public domain.

name: iso

on:
  pull_request:
    paths: ['**iso**']
  workflow_dispatch:

jobs:
  iso:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build ISO
        run: sudo bash iso/src/build.sh

      # https://stackoverflow.com/a/69977763
      - name: Change ownership
        run: |
          USER=$(whoami)
          sudo chown $USER:$USER iso/bin/bootiso/install.iso

      - name: Package
        uses: actions/upload-artifact@v5
        with:
          name: server.iso
          path: iso/bin/bootiso/install.iso
          retention-days: 7
