# This is free and unencumbered software released into the public domain.

name: jellyfin

on:
  pull_request:
    paths: ['**/jellyfin.yaml', 'jellyfin/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['jellyfin/src/**']
  workflow_dispatch:

jobs:
  jellyfin:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: jellyfin }
