# This is free and unencumbered software released into the public domain.

name: opencloud

on:
  pull_request:
    paths: ['**/opencloud.yaml', 'opencloud/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['opencloud/src/**']
  workflow_dispatch:

jobs:
  opencloud:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: opencloud }
