# This is free and unencumbered software released into the public domain.

name: outline

on:
  pull_request:
    paths: ['**/outline.yaml', 'outline/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['outline/src/**']
  workflow_dispatch:

jobs:
  outline:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: outline }
