# This is free and unencumbered software released into the public domain.

name: penpot

on:
  pull_request:
    paths: ['**/penpot.yaml', 'penpot/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['penpot/src/**']
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: penpot/backend }

  exporter:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: penpot/exporter }

  frontend:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: penpot/frontend }
