# This is free and unencumbered software released into the public domain.

name: postgres

on:
  pull_request:
    paths: ['**/postgres.yaml', 'postgres/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['postgres/src/**']
  workflow_dispatch:

jobs:
  postgres:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: postgres }
