# This is free and unencumbered software released into the public domain.

name: purge
on:
  pull_request:
    paths:
      - scripts/src/purge.py
      - pyproject.toml
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v6

      - name: pipenv
        run: pip install uv

      # Must use PAT to work around known issue in actions:
      # https://github.com/cli/cli/issues/9606#issuecomment-2433338481
      - name: run
        run: uv run scripts/src/purge.py
        env:
          GITHUB_TOKEN: ${{ secrets.CONTAINER_PURGE }}
