# This is free and unencumbered software released into the public domain.

name: renovate

on:
  pull_request:
    paths: ['**renovate**']
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Renovate
        uses: renovatebot/github-action@v43.0.20
        with:
          configurationFile: renovate/runner/config.js
          token: ${{ secrets.RENOVATE_WORKFLOW }}
