# This is free and unencumbered software released into the public domain.

name: seaweedfs

on:
  pull_request:
    paths: ['**/seaweedfs.yaml', 'seaweedfs/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['seaweedfs/src/**']
  workflow_dispatch:

jobs:
  seaweedfs:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { specifier: seaweedfs }
