# This is free and unencumbered software released into the public domain.

name: vector

on:
  pull_request:
    paths: ['**/vector.yaml', 'vector/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['vector/src/**']
  workflow_dispatch:

jobs:
  privileged:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: vector/src/privileged.dockerfile }

  unprivileged:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: vector/src/unprivileged.dockerfile }
