# This is free and unencumbered software released into the public domain.

name: victorialogs

on:
  pull_request:
    paths: ['**/victorialogs.yaml', 'victorialogs/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['victorialogs/src/**']
  workflow_dispatch:

jobs:
  victorialogs:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: victorialogs/src/victorialogs.dockerfile }
